trial:
  duration_in_days: 14

plans:
  Bronze:
    monthly_cost: 50
    users: 1
    description: 1 user and access to all features
  Silver:
    monthly_cost: 100
    users: 3
    description: Up to 3 users and access to all features
  Gold:
    monthly_cost: 150
    users: 10
    description: Up to 10 users and access to all features
  Platinum:
    monthly_cost: 150
    users: 30
    description: Up to 30 users and access to all features
  Enterprise:
    monthly_cost: Contact us
    users: 1000
    description: Enough users to fit your team's needs and access to all features
