class AddIndexesToIncreaseSpeed < ActiveRecord::Migration
  def change
    add_index :account_credits, :organization_id, :name => 'index_account_credits_on_org_id'
    add_index :appointments, :organization_id, :name => 'index_appointments_on_org_id'
    add_index :appointments, :user_id, :name => 'index_appointments_on_user_id'
    add_index :appointments, :job_id, :name => 'index_appointments_on_job_id'
    add_index :communications, :job_id, :name => 'index_communications_on_job_id'
    add_index :communications, :user_id, :name => 'index_communications_on_user_id'
    add_index :communications, :organization_id, :name => 'index_communications_on_org_id'
    add_index :contacts, :organization_id, :name => 'index_contacts_on_org_id'
    add_index :crews, :organization_id, :name => 'index_crews_on_org_id'
    add_index :email_templates, :organization_id, :name => 'index_email_templates_on_org_id'
    add_index :expenses, :job_id, :name => 'index_expenses_on_job_id'
    add_index :expenses, :organization_id, :name => 'index_expenses_on_org_id'
    add_index :jobs, :lead_source_id, :name => 'index_jobs_on_lead_source_id'
    add_index :jobs, :contact_id, :name => 'index_jobs_on_contact_id'
    add_index :jobs, :crew_id, :name => 'index_jobs_on_crew_id'
    add_index :jobs, :organization_id, :name => 'index_jobs_on_org_id'
    add_index :lead_sources, :organization_id, :name => 'index_lead_sources_on_org_id'
    add_index :payments, :job_id, :name => 'index_payments_on_job_id'
    add_index :payments, :organization_id, :name => 'index_payments_on_org_id'
    add_index :proposal_item_responses, :proposal_template_item_id, :name => 'index_proposal_item_responses_on_template_item_id'
    add_index :proposal_item_responses, :proposal_section_response_id, :name => 'index_proposal_item_responses_on_section_response_id'
    add_index :proposal_section_responses, :proposal_template_section_id, :name => 'index_proposal_section_responses_on_template_section_id'
    add_index :proposal_section_responses, :proposal_id, :name => 'index_proposal_section_responses_on_proposal_id'
    add_index :proposal_template_items, :proposal_template_section_id, :name => 'index_proposal_template_items_on_template_section_id'
    add_index :proposal_template_sections, :proposal_template_id, :name => 'index_proposal_template_sections_on_template_id'
    add_index :proposal_templates, :organization_id, :name => 'index_proposal_templates_on_org_id'
    add_index :proposals, :job_id, :name => 'index_proposals_on_job_id'
    add_index :proposals, :proposal_template_id, :name => 'index_proposals_on_template_id'
    add_index :proposals, :sales_person_id, :name => 'index_proposals_on_sales_person_id'
    add_index :proposals, :contractor_id, :name => 'index_proposals_on_contractor_id'
    add_index :proposals, :organization_id, :name => 'index_proposals_on_org_id'
    add_index :proposals, :customer_sig_user_id, :name => 'index_proposals_on_customer_sig_user_id'
    add_index :proposals, :contractor_sig_user_id, :name => 'index_proposals_on_contractor_sig_user_id'
    add_index :proposals, :guid, :name => 'index_proposals_on_guid'
    add_index :timecards, :job_id, :name => 'index_timecards_on_job_id'
    add_index :timecards, :organization_id, :name => 'index_timecards_on_org_id'
    add_index :timecards, :user_id, :name => 'index_timecards_on_user_id'
    add_index :users, :organization_id, :name => 'index_users_on_org_id'
  end
end
